export const GAME_STATE = {
    NOT_INITIALIZED: "NOT_INITIALIZED",
    INITIALIZING: "INITIALIZING",
    ASK: "ASK",
    ANSWER: "ANSWER",
    OVER: "OVER"
}

export const GAME_STATE_ACTION = {
    SET_GAME_STATE: "SET_GAME_STATE",
    SET_PLAYER2: "SET_PLAYER2",
    SET_INITIALIZING: "SET_INITIALIZING",
    SET_ASK: "SET_ASK",
    SET_ANSWER: "SET_ANSWER",
    SET_SCORE: "SET_SCORE",
    GAME_OVER: "GAME_OVER"
}